server:
  port: 80
spring:
  threads:
    virtual:
      enabled: false
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB


app:
  storagePath: ./fccn/files
  seedNodes:
    - "http://localhost:8080"
  fccnMnemonic: "phone poem two excuse lift surge power member ghost faith media ethics"
